[package]
name = "gxt-cli"
description.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
readme = "../README.md"

[dependencies]
serde_json.workspace = true
clap = { version = "4.5", features = ["derive"] }
anyhow = "1"
gxt = { version = "0.8.0", path = "../gxt" }

[[bin]]
name = "gxt"
path = "src/main.rs"
