[package]
name = "gxt-cli"
version = "1.2.0"
description.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
readme = "../README.md"

[dependencies]
gxt.workspace = true
serde_json.workspace = true
clap = { version = "4.5", features = ["derive"] }
anyhow = "1"

[[bin]]
name = "gxt"
path = "src/main.rs"
